import { db } from '@/db';
import { tickets } from '@/db/schema';

async function main() {
    const sampleTickets = [
        {
            title: 'Laptop not charging - battery issue',
            description: 'My Dell laptop suddenly stopped charging yesterday. The charging indicator light does not turn on when plugged in. I have tried different power outlets and the same issue persists. Battery is currently at 5% and I need this resolved urgently as I have an important presentation tomorrow.',
            status: 'in_progress',
            priority: 'urgent',
            category: 'hardware',
            requesterName: 'Robert Anderson',
            requesterEmail: 'robert.anderson@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-06-15T09:30:00').toISOString(),
            updatedAt: new Date('2024-06-15T10:15:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Monitor display flickering',
            description: 'External monitor connected to my laptop keeps flickering every few minutes. The flickering lasts for about 5-10 seconds. I have checked the cable connections and they seem fine. This started happening after the latest Windows update.',
            status: 'resolved',
            priority: 'medium',
            category: 'hardware',
            requesterName: 'Jennifer Wilson',
            requesterEmail: 'jennifer.wilson@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-05-20T14:20:00').toISOString(),
            updatedAt: new Date('2024-05-21T11:30:00').toISOString(),
            resolvedAt: new Date('2024-05-21T11:30:00').toISOString(),
        },
        {
            title: 'Microsoft Office license activation failed',
            description: 'I am unable to activate my Microsoft Office 365 license. When I try to open Word or Excel, it prompts me to activate the product. I have entered the license key provided but it says "This product key has already been used". Need assistance to resolve this issue.',
            status: 'closed',
            priority: 'high',
            category: 'software',
            requesterName: 'Michael Thompson',
            requesterEmail: 'michael.thompson@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-04-10T08:45:00').toISOString(),
            updatedAt: new Date('2024-04-10T16:20:00').toISOString(),
            resolvedAt: new Date('2024-04-10T16:20:00').toISOString(),
        },
        {
            title: 'Cannot connect to WiFi network',
            description: 'My laptop cannot detect the office WiFi network. Other devices can connect without issues. I have restarted my laptop multiple times but the problem persists. Network troubleshooter shows "Windows cannot find any networks".',
            status: 'open',
            priority: 'high',
            category: 'network',
            requesterName: 'Lisa Martinez',
            requesterEmail: 'lisa.martinez@company.com',
            assignedTo: null,
            createdAt: new Date('2024-06-18T10:15:00').toISOString(),
            updatedAt: new Date('2024-06-18T10:15:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Forgot password - need reset',
            description: 'I forgot my domain password and need it reset. I have tried the self-service password reset portal but it says my security questions are not on file. Can someone help me reset my password? My user ID is lmartinez.',
            status: 'resolved',
            priority: 'medium',
            category: 'access',
            requesterName: 'David Chen',
            requesterEmail: 'david.chen@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-06-01T09:00:00').toISOString(),
            updatedAt: new Date('2024-06-01T09:45:00').toISOString(),
            resolvedAt: new Date('2024-06-01T09:45:00').toISOString(),
        },
        {
            title: 'Printer paper jam',
            description: 'The HP printer on the 3rd floor has a paper jam. I have tried to remove the jammed paper but it appears to be stuck inside. The printer display shows "Paper Jam in Tray 2". Multiple people need to print documents urgently.',
            status: 'closed',
            priority: 'medium',
            category: 'hardware',
            requesterName: 'Amanda Foster',
            requesterEmail: 'amanda.foster@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-03-15T13:30:00').toISOString(),
            updatedAt: new Date('2024-03-15T14:45:00').toISOString(),
            resolvedAt: new Date('2024-03-15T14:45:00').toISOString(),
        },
        {
            title: 'Unable to install Adobe Acrobat',
            description: 'I need to install Adobe Acrobat Pro on my laptop for PDF editing. When I try to install from the company software portal, I get an error message "Installation failed - Error code 1603". I have administrator rights on my machine.',
            status: 'in_progress',
            priority: 'low',
            category: 'software',
            requesterName: 'Christopher Davis',
            requesterEmail: 'christopher.davis@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-06-10T11:20:00').toISOString(),
            updatedAt: new Date('2024-06-12T09:30:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Internet connection dropping frequently',
            description: 'My internet connection keeps dropping every 10-15 minutes. I am connected via Ethernet cable to the network port at my desk. This is affecting my ability to attend video conferences and complete work tasks. Please investigate.',
            status: 'open',
            priority: 'high',
            category: 'network',
            requesterName: 'Rebecca Taylor',
            requesterEmail: 'rebecca.taylor@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-06-17T08:50:00').toISOString(),
            updatedAt: new Date('2024-06-17T09:10:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Account locked after multiple failed login attempts',
            description: 'My account has been locked due to multiple failed login attempts. I was trying different passwords as I could not remember the correct one. Now I cannot access my email or any company systems. Please unlock my account urgently.',
            status: 'resolved',
            priority: 'urgent',
            category: 'access',
            requesterName: 'James Rodriguez',
            requesterEmail: 'james.rodriguez@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-05-28T07:30:00').toISOString(),
            updatedAt: new Date('2024-05-28T08:15:00').toISOString(),
            resolvedAt: new Date('2024-05-28T08:15:00').toISOString(),
        },
        {
            title: 'Request new software installation',
            description: 'I need Slack desktop application installed on my laptop for team communication. This is required for the new project I am working on. Please install and configure Slack with my company email address.',
            status: 'closed',
            priority: 'low',
            category: 'other',
            requesterName: 'Patricia Moore',
            requesterEmail: 'patricia.moore@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-04-25T10:00:00').toISOString(),
            updatedAt: new Date('2024-04-26T14:30:00').toISOString(),
            resolvedAt: new Date('2024-04-26T14:30:00').toISOString(),
        },
        {
            title: 'Keyboard keys not responding',
            description: 'Several keys on my laptop keyboard are not responding - specifically the letters E, R, and T. This makes typing very difficult. The laptop is only 6 months old. Need replacement keyboard or external keyboard as temporary solution.',
            status: 'in_progress',
            priority: 'high',
            category: 'hardware',
            requesterName: 'Daniel White',
            requesterEmail: 'daniel.white@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-06-14T15:45:00').toISOString(),
            updatedAt: new Date('2024-06-16T10:20:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Outlook keeps crashing when opening attachments',
            description: 'Microsoft Outlook crashes every time I try to open email attachments. The application freezes and then closes. I have tried restarting Outlook and my computer but the issue continues. This is preventing me from accessing important documents.',
            status: 'resolved',
            priority: 'medium',
            category: 'software',
            requesterName: 'Sarah Miller',
            requesterEmail: 'sarah.miller@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-05-05T09:15:00').toISOString(),
            updatedAt: new Date('2024-05-06T11:00:00').toISOString(),
            resolvedAt: new Date('2024-05-06T11:00:00').toISOString(),
        },
        {
            title: 'Slow network speed in conference room',
            description: 'WiFi connection in Conference Room B is extremely slow. Speed tests show less than 1 Mbps download speed. This is affecting our client presentations and video conferences. All other areas of the office have normal speeds.',
            status: 'open',
            priority: 'medium',
            category: 'network',
            requesterName: 'Kevin Brown',
            requesterEmail: 'kevin.brown@company.com',
            assignedTo: null,
            createdAt: new Date('2024-06-16T13:25:00').toISOString(),
            updatedAt: new Date('2024-06-16T13:25:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Need access to Finance shared folder',
            description: 'I recently joined the Finance team and need access to the Finance shared drive on the network. My manager has approved this request. My username is kwilson. Please grant me read and write permissions.',
            status: 'closed',
            priority: 'low',
            category: 'access',
            requesterName: 'Karen Wilson',
            requesterEmail: 'karen.wilson@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-03-20T10:30:00').toISOString(),
            updatedAt: new Date('2024-03-21T09:15:00').toISOString(),
            resolvedAt: new Date('2024-03-21T09:15:00').toISOString(),
        },
        {
            title: 'Laptop upgrade request',
            description: 'My current laptop is 4 years old and is very slow. It takes more than 5 minutes to boot up and applications freeze frequently. I work with large data files and need a more powerful machine. Requesting laptop upgrade approval.',
            status: 'in_progress',
            priority: 'low',
            category: 'other',
            requesterName: 'Thomas Anderson',
            requesterEmail: 'thomas.anderson@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-06-05T14:00:00').toISOString(),
            updatedAt: new Date('2024-06-10T11:30:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Mouse not working',
            description: 'My wireless mouse stopped working this morning. I have replaced the batteries but it still does not connect to the laptop. The USB receiver is properly plugged in. Need a replacement mouse to continue working.',
            status: 'resolved',
            priority: 'medium',
            category: 'hardware',
            requesterName: 'Michelle Garcia',
            requesterEmail: 'michelle.garcia@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-04-18T08:30:00').toISOString(),
            updatedAt: new Date('2024-04-18T10:45:00').toISOString(),
            resolvedAt: new Date('2024-04-18T10:45:00').toISOString(),
        },
        {
            title: 'VPN client not connecting',
            description: 'I cannot connect to the company VPN from home. The VPN client shows "Connection timeout" error. I need VPN access to work remotely and access internal systems. This worked fine last week. Please help resolve this urgently.',
            status: 'in_progress',
            priority: 'urgent',
            category: 'software',
            requesterName: 'Brian Lee',
            requesterEmail: 'brian.lee@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-06-18T07:15:00').toISOString(),
            updatedAt: new Date('2024-06-18T08:30:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Cannot access shared network drive',
            description: 'I am unable to access the Marketing shared drive (\\\\server\\marketing). When I try to open it, I get "Access Denied" error. I had access until yesterday. Need this resolved as I have files there that I need for today\'s presentation.',
            status: 'resolved',
            priority: 'high',
            category: 'network',
            requesterName: 'Nancy Clark',
            requesterEmail: 'nancy.clark@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-05-15T09:00:00').toISOString(),
            updatedAt: new Date('2024-05-15T10:30:00').toISOString(),
            resolvedAt: new Date('2024-05-15T10:30:00').toISOString(),
        },
        {
            title: 'New employee onboarding - setup required',
            description: 'New employee John Smith starts on Monday. Need to set up laptop, email account, network access, and install standard software suite. Also need to create accounts for all internal systems. Manager: Sarah Johnson. Department: Sales.',
            status: 'open',
            priority: 'medium',
            category: 'access',
            requesterName: 'HR Department',
            requesterEmail: 'hr@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-06-17T14:00:00').toISOString(),
            updatedAt: new Date('2024-06-17T14:00:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'General IT consultation needed',
            description: 'Need consultation on best practices for data backup and security for our department. Would like to schedule a 30-minute meeting to discuss options and recommendations. Available any time this week.',
            status: 'closed',
            priority: 'low',
            category: 'other',
            requesterName: 'Steven Harris',
            requesterEmail: 'steven.harris@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-02-10T11:00:00').toISOString(),
            updatedAt: new Date('2024-02-12T15:30:00').toISOString(),
            resolvedAt: new Date('2024-02-12T15:30:00').toISOString(),
        },
        {
            title: 'Docking station not detecting monitors',
            description: 'My Dell docking station is not detecting my dual monitors. The monitors work fine when connected directly to the laptop. I have tried disconnecting and reconnecting everything. The docking station power light is on.',
            status: 'in_progress',
            priority: 'medium',
            category: 'hardware',
            requesterName: 'Laura Martinez',
            requesterEmail: 'laura.martinez@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-06-13T10:45:00').toISOString(),
            updatedAt: new Date('2024-06-14T09:20:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Software update stuck at 50%',
            description: 'Windows update has been stuck at 50% for over 2 hours. The progress bar is not moving and the laptop is unresponsive. I am afraid to force shut down as it might corrupt the system. Need guidance on what to do.',
            status: 'resolved',
            priority: 'high',
            category: 'software',
            requesterName: 'Richard Walker',
            requesterEmail: 'richard.walker@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-05-22T14:30:00').toISOString(),
            updatedAt: new Date('2024-05-22T16:45:00').toISOString(),
            resolvedAt: new Date('2024-05-22T16:45:00').toISOString(),
        },
        {
            title: 'VPN connection timeout',
            description: 'VPN connection keeps timing out after 5-10 minutes. I have to reconnect multiple times throughout the day. This is disrupting my work flow. Internet connection is stable when not using VPN.',
            status: 'open',
            priority: 'medium',
            category: 'network',
            requesterName: 'Maria Rodriguez',
            requesterEmail: 'maria.rodriguez@company.com',
            assignedTo: null,
            createdAt: new Date('2024-06-18T11:30:00').toISOString(),
            updatedAt: new Date('2024-06-18T11:30:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Cannot access HR portal',
            description: 'I am unable to access the HR portal to submit my timesheet. The page shows "403 Forbidden" error. I have tried from different browsers with the same result. My deadline for timesheet submission is today.',
            status: 'resolved',
            priority: 'high',
            category: 'access',
            requesterName: 'George Thompson',
            requesterEmail: 'george.thompson@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-04-30T13:15:00').toISOString(),
            updatedAt: new Date('2024-04-30T15:00:00').toISOString(),
            resolvedAt: new Date('2024-04-30T15:00:00').toISOString(),
        },
        {
            title: 'Equipment return for terminated employee',
            description: 'Employee Jane Doe (terminated 06/15/2024) needs to return laptop, monitor, keyboard, and mouse. Please arrange pickup or provide return instructions. Equipment tag numbers: LAP-1234, MON-5678, KEY-9012, MOU-3456.',
            status: 'in_progress',
            priority: 'low',
            category: 'other',
            requesterName: 'HR Department',
            requesterEmail: 'hr@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-06-15T16:00:00').toISOString(),
            updatedAt: new Date('2024-06-17T10:00:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Application permission denied error',
            description: 'When trying to run the Salesforce desktop application, I get "Permission Denied" error. The application was working fine until this morning. I have not made any changes to my computer. Need this resolved to access customer data.',
            status: 'closed',
            priority: 'high',
            category: 'software',
            requesterName: 'Andrew Martinez',
            requesterEmail: 'andrew.martinez@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-03-08T09:45:00').toISOString(),
            updatedAt: new Date('2024-03-08T12:30:00').toISOString(),
            resolvedAt: new Date('2024-03-08T12:30:00').toISOString(),
        },
        {
            title: 'Email not syncing on mobile device',
            description: 'Company email is not syncing on my iPhone. I can send and receive emails on my laptop but not on mobile. I have tried removing and re-adding the account. Getting error "Cannot connect to server". Need mobile email access for work.',
            status: 'resolved',
            priority: 'medium',
            category: 'network',
            requesterName: 'Jessica Taylor',
            requesterEmail: 'jessica.taylor@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-05-10T08:20:00').toISOString(),
            updatedAt: new Date('2024-05-11T10:15:00').toISOString(),
            resolvedAt: new Date('2024-05-11T10:15:00').toISOString(),
        },
        {
            title: 'Multi-factor authentication not working',
            description: 'MFA authentication code from my phone is not being accepted. I am entering the correct 6-digit code but it says "Invalid code". I cannot access my email or any company systems. This is blocking me from working.',
            status: 'open',
            priority: 'urgent',
            category: 'access',
            requesterName: 'William Johnson',
            requesterEmail: 'william.johnson@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-06-18T08:00:00').toISOString(),
            updatedAt: new Date('2024-06-18T08:30:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Setup new conference room technology',
            description: 'New conference room on 5th floor needs AV equipment setup. Requires projector installation, wireless presentation system, conference phone, and video conferencing setup. Room will be used starting next week.',
            status: 'in_progress',
            priority: 'medium',
            category: 'other',
            requesterName: 'Facilities Manager',
            requesterEmail: 'facilities@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-06-12T09:00:00').toISOString(),
            updatedAt: new Date('2024-06-16T14:30:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Laptop screen has dead pixels',
            description: 'My laptop screen has developed several dead pixels in the center. There are about 10-15 black dots that are very noticeable on light backgrounds. This is affecting my ability to work with documents and spreadsheets. Laptop is still under warranty.',
            status: 'closed',
            priority: 'low',
            category: 'hardware',
            requesterName: 'Elizabeth Davis',
            requesterEmail: 'elizabeth.davis@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-01-15T11:00:00').toISOString(),
            updatedAt: new Date('2024-01-20T15:45:00').toISOString(),
            resolvedAt: new Date('2024-01-20T15:45:00').toISOString(),
        },
        {
            title: 'Antivirus software blocking work application',
            description: 'The antivirus software is blocking our custom in-house application. Every time I try to run it, I get a security warning and the application is quarantined. I need this application to process client orders. Can you whitelist this application?',
            status: 'resolved',
            priority: 'high',
            category: 'software',
            requesterName: 'Charles Wilson',
            requesterEmail: 'charles.wilson@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-04-05T10:30:00').toISOString(),
            updatedAt: new Date('2024-04-05T14:20:00').toISOString(),
            resolvedAt: new Date('2024-04-05T14:20:00').toISOString(),
        },
        {
            title: 'Network printer showing offline',
            description: 'The HP LaserJet printer in the Marketing department shows as offline on all computers. The printer power is on and shows ready on the display panel. Cannot print any documents. Multiple users are affected.',
            status: 'open',
            priority: 'medium',
            category: 'network',
            requesterName: 'Susan Anderson',
            requesterEmail: 'susan.anderson@company.com',
            assignedTo: null,
            createdAt: new Date('2024-06-17T15:20:00').toISOString(),
            updatedAt: new Date('2024-06-17T15:20:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Need elevated permissions for software installation',
            description: 'I need to install Python and several development tools on my laptop for a new project. I do not have administrator rights to install software. Can you either install these tools for me or temporarily grant admin access?',
            status: 'in_progress',
            priority: 'low',
            category: 'access',
            requesterName: 'Mark Thompson',
            requesterEmail: 'mark.thompson@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-06-11T13:45:00').toISOString(),
            updatedAt: new Date('2024-06-13T11:00:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Request additional monitor',
            description: 'I would like to request a second monitor for my workstation. I work with multiple applications and spreadsheets simultaneously and a dual monitor setup would significantly improve my productivity. My manager has approved this request.',
            status: 'closed',
            priority: 'low',
            category: 'other',
            requesterName: 'Jennifer Brown',
            requesterEmail: 'jennifer.brown@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-02-28T10:15:00').toISOString(),
            updatedAt: new Date('2024-03-05T16:30:00').toISOString(),
            resolvedAt: new Date('2024-03-05T16:30:00').toISOString(),
        },
        {
            title: 'Laptop overheating and shutting down',
            description: 'My laptop keeps overheating and shutting down unexpectedly. The fan is running very loudly and the bottom of the laptop gets extremely hot. This happens especially when running multiple applications. Cannot complete work tasks reliably.',
            status: 'in_progress',
            priority: 'high',
            category: 'hardware',
            requesterName: 'Anthony Garcia',
            requesterEmail: 'anthony.garcia@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-06-14T11:30:00').toISOString(),
            updatedAt: new Date('2024-06-15T14:00:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Teams video freezing during calls',
            description: 'Microsoft Teams video keeps freezing during calls. Audio works fine but video freezes every few minutes. Other participants report they cannot see me properly. This is affecting client meetings. Internet connection is stable.',
            status: 'resolved',
            priority: 'medium',
            category: 'software',
            requesterName: 'Barbara Martinez',
            requesterEmail: 'barbara.martinez@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-05-18T09:30:00').toISOString(),
            updatedAt: new Date('2024-05-19T11:45:00').toISOString(),
            resolvedAt: new Date('2024-05-19T11:45:00').toISOString(),
        },
        {
            title: 'Cannot map network drive',
            description: 'I am trying to map the shared department drive but keep getting "Network path not found" error. I have used the correct path \\\\fileserver\\dept\\sales. My colleague sitting next to me can access it without issues. Need help mapping this drive.',
            status: 'open',
            priority: 'low',
            category: 'network',
            requesterName: 'Paul Wilson',
            requesterEmail: 'paul.wilson@company.com',
            assignedTo: null,
            createdAt: new Date('2024-06-18T14:15:00').toISOString(),
            updatedAt: new Date('2024-06-18T14:15:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'External hard drive not recognized',
            description: 'My external USB hard drive is not being recognized by my laptop. I have tried different USB ports and the drive is not showing up in File Explorer. The drive power light is on. This drive contains important backup files.',
            status: 'resolved',
            priority: 'high',
            category: 'hardware',
            requesterName: 'Dorothy Johnson',
            requesterEmail: 'dorothy.johnson@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-04-22T13:00:00').toISOString(),
            updatedAt: new Date('2024-04-23T10:30:00').toISOString(),
            resolvedAt: new Date('2024-04-23T10:30:00').toISOString(),
        },
        {
            title: 'Chrome browser keeps crashing',
            description: 'Google Chrome crashes multiple times per day. It happens randomly while browsing or accessing web applications. I have tried clearing cache and cookies but the issue persists. Firefox works fine but I prefer Chrome for work.',
            status: 'in_progress',
            priority: 'medium',
            category: 'software',
            requesterName: 'Kenneth Moore',
            requesterEmail: 'kenneth.moore@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-06-10T08:45:00').toISOString(),
            updatedAt: new Date('2024-06-12T15:20:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Wireless access point not working',
            description: 'WiFi access point in the east wing of the building is not working. Employees in that area cannot connect to WiFi. The access point lights are not on. This is affecting about 15 employees who need internet access for their work.',
            status: 'open',
            priority: 'urgent',
            category: 'network',
            requesterName: 'Facilities Manager',
            requesterEmail: 'facilities@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-06-18T07:45:00').toISOString(),
            updatedAt: new Date('2024-06-18T08:15:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Shared calendar not syncing',
            description: 'My Outlook shared calendar is not syncing with other team members. When I create an appointment, it does not show up on their calendars. I can see their appointments but they cannot see mine. This is causing scheduling conflicts.',
            status: 'closed',
            priority: 'medium',
            category: 'software',
            requesterName: 'Carol White',
            requesterEmail: 'carol.white@company.com',
            assignedTo: 'Sarah Johnson',
            createdAt: new Date('2024-03-12T10:00:00').toISOString(),
            updatedAt: new Date('2024-03-13T14:15:00').toISOString(),
            resolvedAt: new Date('2024-03-13T14:15:00').toISOString(),
        },
        {
            title: 'Laptop battery draining quickly',
            description: 'My laptop battery is draining very quickly. Fully charged battery lasts only about 2 hours instead of the usual 6-8 hours. Battery health shows 85% in system settings. This is affecting my ability to work in meetings away from my desk.',
            status: 'resolved',
            priority: 'low',
            category: 'hardware',
            requesterName: 'Sandra Taylor',
            requesterEmail: 'sandra.taylor@company.com',
            assignedTo: 'John Smith',
            createdAt: new Date('2024-05-02T14:30:00').toISOString(),
            updatedAt: new Date('2024-05-08T11:00:00').toISOString(),
            resolvedAt: new Date('2024-05-08T11:00:00').toISOString(),
        },
        {
            title: 'File corruption in shared drive',
            description: 'Several Excel files in our shared department folder are showing as corrupted. When trying to open them, Excel displays "File is corrupted and cannot be opened" error. These files contain critical financial data. Need immediate assistance.',
            status: 'in_progress',
            priority: 'urgent',
            category: 'network',
            requesterName: 'Finance Department',
            requesterEmail: 'finance@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-06-17T16:30:00').toISOString(),
            updatedAt: new Date('2024-06-18T09:00:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Need software training',
            description: 'I need training on the new project management software that was recently deployed. I am not familiar with the interface and features. Would like to schedule a training session or get access to training materials.',
            status: 'open',
            priority: 'low',
            category: 'other',
            requesterName: 'Margaret Harris',
            requesterEmail: 'margaret.harris@company.com',
            assignedTo: null,
            createdAt: new Date('2024-06-16T11:00:00').toISOString(),
            updatedAt: new Date('2024-06-16T11:00:00').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Webcam not working in Teams',
            description: 'My laptop webcam is not working in Microsoft Teams meetings. The camera works fine in the Windows Camera app but Teams shows "Camera not found". Other applications can access the camera without issues. Need this fixed for client meetings.',
            status: 'closed',
            priority: 'high',
            category: 'software',
            requesterName: 'Gary Anderson',
            requesterEmail: 'gary.anderson@company.com',
            assignedTo: 'Mike Chen',
            createdAt: new Date('2024-01-25T08:15:00').toISOString(),
            updatedAt: new Date('2024-01-25T12:45:00').toISOString(),
            resolvedAt: new Date('2024-01-25T12:45:00').toISOString(),
        },
        {
            title: 'Spam emails bypassing filter',
            description: 'I am receiving numerous spam emails that are bypassing the email filter. Getting 20-30 spam messages daily in my inbox. Some appear to be phishing attempts. Please review and update spam filter settings for my account.',
            status: 'resolved',
            priority: 'medium',
            category: 'network',
            requesterName: 'Betty Clark',
            requesterEmail: 'betty.clark@company.com',
            assignedTo: 'Emily Rodriguez',
            createdAt: new Date('2024-06-08T10:20:00').toISOString(),
            updatedAt: new Date('2024-06-10T15:30:00').toISOString(),
            resolvedAt: new Date('2024-06-10T15:30:00').toISOString(),
        },
        {
            title: 'Bluetooth headset keeps disconnecting',
            description: 'My Bluetooth headset keeps disconnecting from laptop during calls. Connection drops every 5-10 minutes. I have to manually reconnect each time. This is very disruptive during important conference calls. Headset works fine with my phone.',
            status: 'in_progress',
            priority: 'medium',
            category: 'hardware',
            requesterName: 'Edward Lewis',
            requesterEmail: 'edward.lewis@company.com',
            assignedTo: 'David Brown',
            createdAt: new Date('2024-06-11T09:15:00').toISOString(),
            updatedAt: new Date('2024-06-13T14:45:00').toISOString(),
            resolvedAt: null,
        },
    ];

    await db.insert(tickets).values(sampleTickets);
    
    console.log('✅ Tickets seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});